defmodule Notifications.Channels.Email do
  @moduledoc """
  Email notification channel with HTML/text incident report templates.

  Implements the Notifications.Channel protocol for sending email alerts.
  Supports both HTML and plain text templates for maximum compatibility.
  """

  @behaviour Notifications.Channel

  alias Notifications.Notification
  require Logger

  @type config :: %{
          from: String.t(),
          to: [String.t()],
          cc: [String.t()],
          bcc: [String.t()],
          reply_to: String.t()
        }

  defstruct config: nil

  @impl true
  def name, do: "Email"

  @impl true
  def validate_config do
    case get_env_config() do
      nil ->
        {:error, :email_not_configured}

      config ->
        if is_binary(config.from) and length(config.to) > 0 do
          :ok
        else
          {:error, :invalid_email_config}
        end
    end
  end

  @impl true
  def send(notification) do
    config = get_env_config()

    case config do
      nil ->
        Logger.warning("Email not configured")
        {:error, :not_configured}

      _config ->
        do_send(notification, config)
    end
  end

  defp do_send(notification, config) do
    subject = build_subject(notification)
    html_body = build_html_body(notification)
    text_body = build_text_body(notification)

    email =
      Swoosh.Email.new(
        from: config.from,
        to: config.to,
        cc: config.cc,
        subject: subject
      )
      |> Swoosh.Email.html_body(html_body)
      |> Swoosh.Email.text_body(text_body)

    email =
      if config.reply_to do
        Swoosh.Email.put_header(email, "Reply-To", config.reply_to)
      else
        email
      end

    Logger.debug("Sending email notification: #{subject}")

    case Swoosh.Api.deliver(email, get_swoosh_adapter()) do
      {:ok, _response} ->
        Logger.info("✓ Email notification sent successfully")
        {:ok, %{status: :sent}}

      {:error, reason} ->
        Logger.error("✗ Email notification failed: #{inspect(reason)}")
        {:error, reason}
    end
  end

  defp build_subject(notification) do
    severity_prefix =
      case notification.severity do
        :critical -> "🚨 CRITICAL"
        :error -> "❌ ERROR"
        :warning -> "⚠️ WARNING"
        :info -> "ℹ️ INFO"
      end

    "[#{severity_prefix}] #{notification.title}"
  end

  defp build_html_body(notification) do
    severity_color = severity_to_color(notification.severity)
    severity_label = Notification.severity_string(notification.severity)
    timestamp = DateTime.to_string(notification.timestamp)

    """
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>#{notification.title}</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { background-color: #{severity_color}; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
        .severity { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; opacity: 0.9; }
        .title { font-size: 24px; font-weight: bold; margin: 10px 0 0 0; }
        .content { padding: 20px; background-color: #f9f9f9; }
        .message { font-size: 16px; line-height: 1.8; }
        .details { margin-top: 20px; border-top: 1px solid #ddd; padding-top: 20px; }
        .details h3 { margin: 0 0 10px 0; color: #666; font-size: 14px; text-transform: uppercase; }
        .details table { width: 100%; border-collapse: collapse; }
        .details td { padding: 8px 0; border-bottom: 1px solid #eee; }
        .details td:first-child { font-weight: bold; color: #666; width: 150px; }
        .url { color: #0066cc; text-decoration: none; word-break: break-all; }
        .url:hover { text-decoration: underline; }
        .footer { padding: 20px; text-align: center; color: #999; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="severity">#{severity_label}</div>
        <h1 class="title">#{notification.title}</h1>
      </div>
      
      <div class="content">
        <div class="message">#{notification.message}</div>
        
        <div class="details">
          <h3>Incident Details</h3>
          <table>
            <tr>
              <td>Severity</td>
              <td>#{severity_label}</td>
            </tr>
            <tr>
              <td>Timestamp</td>
              <td>#{timestamp}</td>
            </tr>
            #{if notification.url, do: "<tr><td>Endpoint</td><td><a href=\"#{notification.url}\" class=\"url\">#{notification.url}</a></td></tr>", else: ""}
          </table>
        </div>
      </div>
      
      <div class="footer">
        <p>This notification was generated by Agent Monitor</p>
      </div>
    </body>
    </html>
    """
  end

  defp build_text_body(notification) do
    severity_label = Notification.severity_string(notification.severity)
    timestamp = DateTime.to_string(notification.timestamp)
    separator = String.duplicate("=", 60)

    """
    #{separator}
    [#{severity_label}] #{notification.title}
    #{separator}

    #{notification.message}

    #{separator}
    Incident Details
    #{separator}

    Severity:    #{severity_label}
    Timestamp:   #{timestamp}
    #{if notification.url, do: "Endpoint:    #{notification.url}", else: ""}

    #{separator}
    Generated by Agent Monitor
    #{separator}
    """
  end

  defp severity_to_color(:info), do: "#3498db"
  defp severity_to_color(:warning), do: "#f39c12"
  defp severity_to_color(:error), do: "#e74c3c"
  defp severity_to_color(:critical), do: "#8b0000"

  defp get_env_config do
    from = System.get_env("EMAIL_FROM")
    to_env = System.get_env("EMAIL_TO")

    if from && to_env do
      %{
        from: from,
        to: String.split(to_env, ",", trim: true),
        cc: parse_env_list("EMAIL_CC"),
        bcc: parse_env_list("EMAIL_BCC"),
        reply_to: System.get_env("EMAIL_REPLY_TO")
      }
    else
      nil
    end
  end

  defp parse_env_list(env_var) do
    case System.get_env(env_var) do
      nil -> []
      val -> String.split(val, ",", trim: true)
    end
  end

  defp get_swoosh_adapter do
    adapter = System.get_env("EMAIL_ADAPTER", "SMTP")
    get_swoosh_adapter(adapter)
  end

  defp get_swoosh_adapter("SMTP") do
    {Swoosh.Adapters.SMTP,
     %{
       relay: System.get_env("SMTP_RELAY", "localhost"),
       port: parse_env_int("SMTP_PORT", 587),
       username: System.get_env("SMTP_USERNAME"),
       password: System.get_env("SMTP_PASSWORD"),
       tls: :if_available,
       auth: :always
     }}
  end

  defp get_swoosh_adapter("SENDGRID") do
    api_key = System.get_env("SENDGRID_API_KEY")

    if api_key do
      {Swoosh.Adapters.Sendgrid, %{api_key: api_key}}
    else
      Logger.warning("SENDGRID adapter selected but no API key configured, falling back to SMTP")
      get_swoosh_adapter("SMTP")
    end
  end

  defp get_swoosh_adapter(adapter) do
    Logger.warning("Unknown email adapter: #{adapter}, using SMTP")
    get_swoosh_adapter("SMTP")
  end

  defp parse_env_int(env_var, default) do
    case System.get_env(env_var) do
      nil -> default
      val -> String.to_integer(val)
    end
  end
end
